version: "3.7"

services:

  redis:
    image: redis
    container_name: tutorial_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  redis-commander:
    container_name: tutorial_redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
  
  rabbit:
    image: rabbitmq
    container_name: tutorial_rabbit
    ports:
      - 5672:5672

  server:
    # container_name: tutorial_backend
    build:
      context: ./
    environment:
      REDIS_URL: redis:6379
      MQ_HOSTNAME: rabbit
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 1000
    ports:
    #  - 5000:5000
      - 5000
    volumes:
      - ./:/var/app
    depends_on:
      - redis
      - rabbit

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - "4000:4000"

  django:
    # container_name: tutorial_backend
    build:
      context: ./hello
    environment:
      REDIS_URL: redis:6379
      MQ_HOSTNAME: rabbit
    ports:
      - 8000
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hello:/code
    depends_on:
      - redis
      - rabbit